### ISSUE TITLE
Lỗi nếu thay đổi dữ liệu tệp json

### ISSUE THREAD

**Issue by loanduong02** [longsc2603/AI_Chatbot_Vietnamese#1]
nếu mình thay đổi dữ liệu trong tệp json thì xuất hiện lỗi này làm sao để fix ạ
ValueError: X has 267 features, but LogisticRegression is expecting 299 features as input.

**Comment by longsc2603** [comment]
Hơi mơ hồ 1 tí, nếu bạn gửi được ảnh đoạn code lỗi lên thì sẽ dễ hơn. Nhưng mình đoán có thể là bạn sai vì khác nhau gì đó lúc train và test, check lại thử xem.

**Comment by loanduong02** [comment]
[image: image.png]
em chỉ thay đổi dòng đó thôi ạ nhưng lại có lỗi. Hiện tại em đang muốn thay
đổi data để làm đồ án chatbot thương mại điện tử. Mong a chỉ em cách fix
với ạ

**Comment by longsc2603** [comment]
![image](https://github.com/longsc2603/AI_Chatbot_Vietnamese/assets/56826526/14a3b6e2-3951-4e28-a582-75284fba06a4)
Sao mình k thấy được ảnh nơi @@

**Comment by loanduong02** [comment]
***@***.***
mail của em đây ạ. anh nhắn qua giúp em cái nha

**Comment by loanduong02** [comment]
anh cho em mail đi ạ em nhắn qua.Hoặc là trong bio em có mail ấy ạ anh nhắn giúp em cũng dc

![unnamed](https://github.com/longsc2603/AI_Chatbot_Vietnamese/assets/142495046/064c972e-4694-4e20-a4aa-9a30ca2768fd)
